export const CATEGORIES = ["All","Strategy","Sports","Idle","Driving","Action","Funny"];

export const GAMES = 
[
  {
    id: "dashmetry",
    title: "Dashmetry",
    featured: true,
    description: "Jump and fly your way through danger in this rhythm-based action platformer!",
    category: "Strategy",
    url: "https://dashmetry.1games.io/",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/322170/capsule_616x353.jpg",
    video: "https://cdn.akamai.steamstatic.com/steam/apps/2036304/movie480.mp4"
  },
  {
    id: "super-liquid-soccer",
    title: "Super Liquid Soccer",
    description: "Play an exciting liquid soccer match against others.",
    category: "Sports",
    url: "https://freetoplayz.github.io/super-liquid-soccer/",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1705130/capsule_616x353.jpg",
  },
  {
    id: "slow-roads",
    title: "Slow Roads",
    description: "A relaxing procedural driving game with scenic routes.",
    category: "Driving",
    url: "https://slowroads.io",
    image: "https://slowroads.io/meta-2.0.0.jpg",
  },
  {
    id: "territorial-io",
    title: "Territorial.io",
    description: "Expand your territory in this fast-paced strategy game.",
    category: "Strategy",
    url: "https://territorial.io/",
    image: "https://territorial.io/apple-touch-icon.png",
  },
  {
    id: "ballistic",
    title: "Ballistic",
    description: "An action-packed arcade shooter with bouncing balls.",
    category: "Action",
    url: "https://classroom10x.github.io/embed/ballistic.html",
    image: "https://play-lh.googleusercontent.com/rkG0jterTbL7_lk5YHBn0Obd-YcRdJ27K-_2EPUkk7jar-X3C4Ad05gDzqdRG4tOvg=w512-h512"
  },
  {
    id: "space-waves",
    title: "Space Waves",
    description: "Navigate space waves in this retro arcade classic.",
    category: "Action",
    url: "https://classroom10x.github.io/embed/space-waves.html",
    image: "https://play-lh.googleusercontent.com/zazE7lsV2Vjf6RBzrbAwQZOYUDoczmhl9YR-ajGAVvPQD1CLrGTDavev5vN01x6nOWo=w512-h512"
  },
  {
    id: "color-tunnel",
    title: "Color Tunnel",
    description: "Dash through an endless tunnel of colors and avoid obstacles.",
    category: "Action",
    url: "https://classroom10x.github.io/embed/color-tunnel.html",
    image: "https://play-lh.googleusercontent.com/sJBwBerXZdNl3PaTyKOq7X1S9j-KnVFh3RAa66s2a8U2qCojRXKXiQEI5QftzREkge4=w512-h512",
  },
  {
    id: "idle-dice",
    title: "Idle Dice",
    description: "Roll the dice to earn points and upgrade your setup.",
    category: "Idle",
    url: "https://classroom10x.github.io/embed/idle-dice.html",
    image: "https://play-lh.googleusercontent.com/ishnQb-SwlFk1Hf0O_48Esy6t9GmdL1jpmal5UIcAmTQ0sSXPEX_iFRplCHH1LLjxuDD=w512-h512",
  },
  {
    id: "a-small-world-cup",
    title: "A Small World Cup",
    description: "Compete in a ragdoll physics soccer tournament.",
    category: "Sports",
    url: "https://classroom10x.github.io/embed/a-small-world-cup.html",
    image: "https://play-lh.googleusercontent.com/R47kNu-wEYMVnoo7rFOXiAHoBvW26KHps65Oi0S6zMF722x0LYqHJUiXRvB_xhsj0CM=w512-h512",
  },
  {
    id: "drift-boss",
    title: "Drift Boss",
    description: "Drift your car through endless tight corners.",
    category: "Driving",
    url: "https://classroom10x.github.io/embed/drift-boss.html",
    image: "https://play-lh.googleusercontent.com/Zu0LoruCtIG45qs6iffZkWqGTuzEWflNoH8TNRtfMJ2NGgJxQGfw8kqSrxKtXGjPqeqFLNsnubW6EnPUJvOi8g=w512-h512",
  },
  {
    id: "subway-surfers",
    title: "Subway Surfers",
    description: "Run from the inspector along the subway tracks.",
    category: "Action",
    url: "https://classroom10x.github.io/embed/subway-surfers.html",
    image: "https://play-lh.googleusercontent.com/rIMQN2JTiHSCj7IezGHkhE39-F66y3Epqlt-iyvveGzT5n0CPOrYDpSePQ7rZBvMJRY=w512-h512",
  },
  {
    id: "we-meme",
    title: "We-Meme.io",
    description: "A funny multiplayer party game about making memes.",
    category: "Funny",
    url: "https://we-meme.io/",
    image: "https://we-meme.io/images/we-meme-meta-img.jpg",
  },
  {
    id: "bloons-td-4",
    title: "Bloons TD 4",
    description: "Pop the bloons before they escape your defenses.",
    category: "Strategy",
    url: "https://ubg89.github.io/BloonsTowerDefense4/",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/960090/capsule_616x353.jpg",
  },
  {
    id: "tony-hawk-4",
    title: "Tony Hawk's Pro Skater 4",
    description: "Skate your way through epic levels and score high combos.",
    category: "Sports",
    url: "https://www.retrogames.cc/embed/42359-tony-hawks-pro-skater-4.html",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2395210/capsule_616x353.jpg",
  },
  {
    id: "fifa-2000",
    title: "FIFA 2000",
    description: "Classic soccer game from 2000.",
    category: "Sports",
    url: "https://www.retrogames.cc/embed/41776-fifa-2000.html",
    image: "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2669320/59500266e56f82c44a42f75519013aac085b05fc/capsule_616x353.jpg?t=1777395910",
  },
  {
    id: "tiny-fishing",
    title: "Tiny Fishing",
    description: "Cast your line and catch the biggest fish in the pond.",
    category: "Sports",
    url: "https://classroom10x.github.io/embed/tiny-fishing.html",
    image: "https://play-lh.googleusercontent.com/BC3ai-Gm7WDOHoRyDTFMYgRtxopZbA9s9DDo3kc4wQJteH7Zzh_sWPDlrfEjsX6vbQ=w512-h512",
  },
  {
    id: "highway-rider-extreme",
    title: "Highway Rider Extreme",
    description: "Weave through traffic on a high-speed motorcycle.",
    category: "Driving",
    url: "https://classroom10x.github.io/embed/highway-rider-extreme.html",
    image: "https://play-lh.googleusercontent.com/wMEx517QbvNZv7tnKcbgDYo2kJK7vzCu3Vj84EkJ-Yko6JaQVcIYjHv8yoC7ZbOf3ZU=w512-h512",
  },
  {
    id: "drive-mad",
    title: "Drive Mad",
    description: "Drive off-road vehicles through tricky obstacle courses.",
    category: "Driving",
    url: "https://inkyedu118.github.io/g20/class-401",
    image: "https://play-lh.googleusercontent.com/vJwCnKoOl9hnyPOphqx0pXXQXRhcX9f747VaJ1GRUldEKTYclYEoZZC0pkgOw3hPXqM=w512-h512",
  },
  {
    id: "burnout-extreme-drift-2",
    title: "Burnout Extreme Drift 2",
    description: "Perform insane drifts in high performance cars.",
    category: "Driving",
    url: "https://inkyedu118.github.io/g177/class-304",
    image: "https://play-lh.googleusercontent.com/TMBmmi25BKODgBNYqwZp_90GAyQ60bDxXNSn680lBw3zhE75sWva5rLgGApgnwaEKw=w512-h512",
  }
];
